# Generated by Django 5.2.3 on 2025-06-20 23:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HubToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_login', models.CharField(max_length=255, verbose_name='Login do Usuário')),
                ('token', models.TextField(verbose_name='Token')),
                ('expires_at', models.DateTimeField(verbose_name='Expira em')),
                ('extracted_at', models.DateTimeField(verbose_name='Extraído em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hub_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Token Hub XP',
                'verbose_name_plural': 'Tokens Hub XP',
                'db_table': 'hub_tokens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TokenExtractionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hub_login', models.CharField(max_length=255, verbose_name='Login Hub XP')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('in_progress', 'Em Progresso'), ('success', 'Sucesso'), ('failed', 'Falhou'), ('cancelled', 'Cancelado')], default='pending', max_length=20, verbose_name='Status')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Iniciado em')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completado em')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Mensagem de Erro')),
                ('token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extraction_logs', to='token_extraction.hubtoken')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extraction_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Extração',
                'verbose_name_plural': 'Logs de Extração',
                'db_table': 'token_extraction_logs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddIndex(
            model_name='hubtoken',
            index=models.Index(fields=['user_login'], name='hub_tokens_user_lo_a53048_idx'),
        ),
        migrations.AddIndex(
            model_name='hubtoken',
            index=models.Index(fields=['expires_at'], name='hub_tokens_expires_76ede8_idx'),
        ),
        migrations.AddIndex(
            model_name='hubtoken',
            index=models.Index(fields=['user', 'is_active'], name='hub_tokens_user_id_84f84b_idx'),
        ),
    ]
