# Docker Compose para Staging/Homologação (sem Nginx)

services:
  # FastAPI Application
  api:
    build:
      context: ./fastapi
      dockerfile: Dockerfile
    container_name: mesa_premium_api_staging
    restart: unless-stopped
    env_file:
      - .env.staging
    environment:
      - ENVIRONMENT=staging
    volumes:
      - ./fastapi/logs:/app/logs
    depends_on:
      - redis
    networks:
      - mesa_premium_network
    ports:
      - "8000:8000"  # Exposição direta para Nginx do servidor

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: mesa_premium_redis_staging
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - mesa_premium_network
    command: redis-server --appendonly yes

networks:
  mesa_premium_network:
    driver: bridge

volumes:
  redis_data:
